# Generated by Django 5.2.5 on 2026-09-17 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='⭐ Trusted by 1000+ Customers', max_length=100)),
                ('headline', models.CharField(default='Book Your', max_length=200)),
                ('headline_highlight', models.CharField(default='India Visa', help_text='This part gets highlighted color', max_length=100)),
                ('headline_suffix', models.CharField(default='Slot Effortlessly', max_length=100)),
                ('description', models.TextField(default='Fast, reliable, and hassle-free visa slot booking services for Medical, Tourist, and Double Entry visas across all IVAC centers.', max_length=500)),
                ('cta_primary_text', models.CharField(default='Explore Services', max_length=50)),
                ('cta_primary_link', models.CharField(default='#services', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Get Help', max_length=50)),
                ('cta_secondary_link', models.CharField(default='#contact', max_length=200)),
                ('stat1_value', models.CharField(default='1000+', max_length=20)),
                ('stat1_label', models.CharField(default='Visas Processed', max_length=50)),
                ('stat2_value', models.CharField(default='99%', max_length=20)),
                ('stat2_label', models.CharField(default='Success Rate', max_length=50)),
                ('stat3_value', models.CharField(default='4.9', max_length=20)),
                ('stat3_label', models.CharField(default='Customer Rating', max_length=50)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/slides/')),
                ('icon_class', models.CharField(default='fas fa-passport', help_text="Font Awesome class e.g. 'fas fa-passport'", max_length=50)),
                ('title', models.CharField(default='Visa Services', max_length=100)),
                ('subtitle', models.CharField(default='Fast & Reliable', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-passport', help_text="Font Awesome class e.g. 'fas fa-briefcase-medical'", max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_label', models.CharField(default='BDT', help_text='Currency label', max_length=20)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('is_popular', models.BooleanField(default=False, help_text="Show 'Most Popular' badge")),
                ('cta_text', models.CharField(default='Book Now', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SlotBooker', max_length=100)),
                ('site_tagline', models.CharField(default='Your Trusted Visa Partner', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone', models.CharField(default='+880 1XXXXXXXXX', max_length=30)),
                ('email', models.EmailField(default='info@example.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='+8801XXXXXXXXX', help_text='Full number with country code, no spaces. e.g. +8801812345678', max_length=30)),
                ('meta_title', models.CharField(default='Visa Slot Booking Services', max_length=200)),
                ('meta_description', models.TextField(default='Professional visa slot booking services for Medical, Tourist, and Double Entry visas', max_length=500)),
                ('footer_about_text', models.TextField(default='We provide fast, reliable, and hassle-free visa slot booking services. Your trusted partner for all visa needs.', max_length=500)),
                ('copyright_text', models.CharField(default='© 2026 SlotBooker. All Rights Reserved.', max_length=200)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-bolt', help_text='Font Awesome class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visa_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order'],
            },
        ),
    ]
